# Usamos Python como base
FROM python:3.12

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de la app
COPY . .

# Instalamos las dependencias
RUN pip install --no-cache-dir fastapi uvicorn

# Exponemos el puerto 8000
EXPOSE 8000

# Comando para ejecutar la API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
